name: Release

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write
  packages: write
  id-token: write # needed for signing with cosign

jobs:
  goreleaser:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.23'
        check-latest: true

    - name: Install cosign
      uses: sigstore/cosign-installer@v3

    - name: Install syft
      uses: anchore/sbom-action/download-syft@v0

    - name: Log in to GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Run GoReleaser
      uses: goreleaser/goreleaser-action@v5
      with:
        distribution: goreleaser
        version: latest
        args: release --clean
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        COSIGN_EXPERIMENTAL: 1

  # Keep the existing Dagger publish for additional container registry support
  publish-additional-registries:
    runs-on: ubuntu-latest
    if: ${{ secrets.DOCKER_REGISTRY != '' }}
    steps:
    - uses: actions/checkout@v4
    
    - name: Extract version from tag
      id: version
      run: echo "VERSION=${GITHUB_REF#refs/tags/}" >> $GITHUB_OUTPUT
    
    - uses: dagger/dagger-for-github@v6
      with:
        verb: call
        module: ./ci
        args: |
          publish 
          --source . 
          --registry ${{ secrets.DOCKER_REGISTRY }}
          --tag ${{ steps.version.outputs.VERSION }}
          --username env:DOCKER_USERNAME
          --password env:DOCKER_PASSWORD
      env:
        DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}