name: Security Checks

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  schedule:
    - cron: '0 0 * * 1' # Weekly on Monday

permissions:
  contents: read
  security-events: write
  # Restrict other permissions
  actions: none
  checks: none
  deployments: none
  issues: none
  packages: none
  pages: none
  pull-requests: none
  repository-projects: none
  statuses: none

jobs:
  gosec:
    name: Go Security Check
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Run Gosec Security Scanner
      uses: securego/gosec@v2.21.5
      with:
        args: '-fmt sarif -out gosec-results.sarif ./...'
    
    - name: Upload SARIF file
      uses: github/codeql-action/upload-sarif@v3
      with:
        sarif_file: gosec-results.sarif

  license-check:
    name: License Compliance Check
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.24'
    
    - name: Install go-licenses
      run: go install github.com/google/go-licenses@latest
    
    - name: Check licenses
      run: |
        go-licenses check ./cmd/... ./internal/... ./pkg/... --disallowed_types=forbidden,restricted,reciprocal

  sbom:
    name: Generate SBOM
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Generate SBOM
      uses: anchore/sbom-action@v0
      with:
        artifact-name: sbom-${{ github.sha }}.json
        format: spdx-json
        output-file: sbom.spdx.json
    
    - name: Upload SBOM
      uses: actions/upload-artifact@v4
      with:
        name: sbom
        path: sbom.spdx.json
        retention-days: 30

  dependency-track:
    name: Track Dependencies
    runs-on: ubuntu-latest
    # Add required permissions for dependency submission
    permissions:
      contents: write  # Required to submit dependencies
      security-events: write  # Required for dependency submission API
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.24'
    
    - name: Submit Dependency Snapshot
      uses: actions/go-dependency-submission@v2
      with:
        go-mod-path: ./go.mod