name: SLSA go releaser
on:
  # Temporarily disabled - SLSA workflow needs debugging
  # push:
  #   tags:
  #     - "v*"
  workflow_dispatch:
    inputs:
      tag:
        description: 'Tag to build'
        required: false
        type: string

permissions:
  contents: write
  actions: read
  id-token: write

jobs:
  args:
    runs-on: ubuntu-latest
    outputs:
      commit-date: ${{ steps.ldflags.outputs.commit-date }}
      commit: ${{ steps.ldflags.outputs.commit }}
      version: ${{ steps.ldflags.outputs.version }}
      tree-state: ${{ steps.ldflags.outputs.tree-state }}
    steps:
      - id: checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: ${{ github.event.inputs.tag || github.ref }}
      - id: ldflags
        run: |
          echo "commit-date=$(git log --date=iso8601-strict -1 --pretty=%ct)" >> "$GITHUB_OUTPUT"
          echo "commit=$GITHUB_SHA" >> "$GITHUB_OUTPUT"
          echo "version=$(git describe --tags --always --dirty | cut -c2-)" >> "$GITHUB_OUTPUT"
          echo "tree-state=$(if git diff --quiet; then echo "clean"; else echo "dirty"; fi)" >> "$GITHUB_OUTPUT"

  build:
    permissions:
      id-token: write
      actions: read
      contents: write
    needs: args
    strategy:
      matrix:
        os: [linux, darwin, windows]
        arch: [amd64, arm64]
        exclude:
          - os: windows
            arch: arm64
    uses: slsa-framework/slsa-github-generator/.github/workflows/builder_go_slsa3.yml@v2.0.0
    with:
      go-version: "1.24"
      evaluated-envs: "COMMIT_DATE:${{needs.args.outputs.commit-date}},COMMIT:${{needs.args.outputs.commit}},VERSION:${{needs.args.outputs.version}},TREE_STATE:${{needs.args.outputs.tree-state}}"
      config-file: .slsa-goreleaser/${{matrix.os}}-${{matrix.arch}}.yml

  verification:
    needs: build
    runs-on: ubuntu-latest
    permissions: read-all
    strategy:
      matrix:
        os: [linux, darwin, windows]
        arch: [amd64, arm64]
        exclude:
          - os: windows
            arch: arm64
    steps:
      - name: Install SLSA verifier
        uses: slsa-framework/slsa-verifier/actions/installer@v2.7.1
      
      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          name: ${{ needs.build.outputs.go-binary-name }}
      
      - name: Download provenance
        uses: actions/download-artifact@v4
        with:
          name: ${{ needs.build.outputs.go-binary-name }}.intoto.jsonl
      
      - name: Verify SLSA provenance
        run: |
          slsa-verifier verify-artifact \
            --provenance-path ${{ needs.build.outputs.go-binary-name }}.intoto.jsonl \
            --source-uri github.com/${{ github.repository }} \
            ${{ needs.build.outputs.go-binary-name }}